-- =====================================================================
-- SQL SETUP - SISTEM ANTRIAN PENYALURAN BERAS BULOG DESA WARGALUYU
-- Jalankan script ini di SQL Editor Supabase Anda
-- =====================================================================

-- 1. Hapus Tabel jika sudah ada sebelumnya (Opsional)
drop table if exists public.logs;
drop table if exists public.current_queue;

-- 2. Buat tabel current_queue untuk melacak data antrian aktif
create table public.current_queue (
    id bigint generated by default as identity primary key,
    nomor_sekarang integer not null default 0,
    nomor_sebelumnya integer not null default 0,
    total_antrian integer not null default 1138,
    status text not null default 'Menuju Meja Verifikasi',
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Buat tabel logs untuk pencatatan riwayat pemanggilan
create table public.logs (
    id bigint generated by default as identity primary key,
    nomor integer not null,
    action text not null, -- E.g. 'PANGGIL', 'LEWAT', 'RESET', 'INPUT_MANUAL'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Masukkan baris awal (default ID = 1) untuk diubah oleh admin
insert into public.current_queue (id, nomor_sekarang, nomor_sebelumnya, total_antrian, status)
values (1, 0, 0, 1138, 'Menuju Meja Verifikasi')
on conflict (id) do nothing;

-- 5. Aktifkan Row Level Security (RLS) demi keamanan
alter table public.current_queue enable row level security;
alter table public.logs enable row level security;

-- 6. Buat Policy RLS agar Publik/Anonymous dapat Membaca/Mengubah (Bisa dibatasi nanti jika diperlukan)
create policy "Allow public read current_queue" on public.current_queue for select using (true);
create policy "Allow public update current_queue" on public.current_queue for update using (true);
create policy "Allow public insert current_queue" on public.current_queue for insert with check (true);

create policy "Allow public read logs" on public.logs for select using (true);
create policy "Allow public insert logs" on public.logs for insert with check (true);

-- 7. Tambahkan tabel ke Publikasi Realtime Supabase
begin;
  -- Hapus dlu jika publikasi sudah ada agar bersih
  alter publication supabase_realtime drop table if exists public.current_queue, public.logs;
  -- Tambahkan kembali ke publikasi realtime
  alter publication supabase_realtime add table public.current_queue;
  alter publication supabase_realtime add table public.logs;
commit;
